### ISSUE TITLE
获取mesos状态失败

### ISSUE THREAD

**Issue by unlikezy** [apache/shardingsphere-elasticjob-cloud#6]
使用mesos1.6.0, 最新版本的elastic-job-cloud(ce7d31b3688de82d4ceddb02ac73ab4a2acc8587)
跑例子程序时, 一直出现这个错误:
```
[ERROR]` 2018-07-17 02:47:28,016 --task-launch-processor RUNNING-- [io.elasticjob.cloud.scheduler.mesos.TaskLaunchScheduledService] Launch task error 
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:158) ~[guava-18.0.jar:na]
	at io.elasticjob.cloud.scheduler.mesos.MesosStateService.fetch(MesosStateService.java:138) ~[elastic-job-cloud-scheduler-3.0.0.M1-SNAPSHOT.jar:na]
	at io.elasticjob.cloud.scheduler.mesos.MesosStateService.executors(MesosStateService.java:115) ~[elastic-job-cloud-scheduler-3.0.0.M1-SNAPSHOT.jar:na]
	at io.elasticjob.cloud.scheduler.mesos.MesosStateService.executors(MesosStateService.java:134) ~[elastic-job-cloud-scheduler-3.0.0.M1-SNAPSHOT.jar:na]
	at io.elasticjob.cloud.scheduler.mesos.FacadeService.loadExecutorInfo(FacadeService.java:337) ~[elastic-job-cloud-scheduler-3.0.0.M1-SNAPSHOT.jar:na]
	at io.elasticjob.cloud.scheduler.mesos.AppConstraintEvaluator.loadAppRunningState(AppConstraintEvaluator.java:77) ~[elastic-job-cloud-scheduler-3.0.0.M1-SNAPSHOT.jar:na]
	at io.elasticjob.cloud.scheduler.mesos.TaskLaunchScheduledService.runOneIteration(TaskLaunchScheduledService.java:109) ~[elastic-job-cloud-scheduler-3.0.0.M1-SNAPSHOT.jar:na]
	at com.google.common.util.concurrent.AbstractScheduledService$1$1.run(AbstractScheduledService.java:174) [guava-18.0.jar:na]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) [guava-18.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_71]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]
```

**Comment by terrymanu** [comment]
我们使用的是1.1.0，之后的版本没再测试，欢迎提交新版本的pr。由于bug时间较长，我先关闭了，有对新版本mesos的需求欢迎讨论pr
